import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";

export default function Home() {
  const onCLickHandler = () => {
    console.log("Hello");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          onCLickHandler={onCLickHandler}
          buttonText="View stores nearby"
        />
      </main>
    </div>
  );
}
